### ISSUE TITLE
[1.11.2] Optifine related crash

### ISSUE THREAD

**Issue by ghost** [sokratis12GR/ArmorPlus#104]
**ArmorPlus Version**:
armorplus-1.11.2-9.5.6.7-beta
JEI: jei_1.11.2-4.2.4.231

**TheDragonLib Version**:
thedragonlib-1.11.2-2.2.3

**MinecraftForge Version**:
forge-1.11.2-13.20.0.2226-universal

**Minecraft Version**:
minecraft_server.1.11.2

**Client or Server?**:
- [x] Client

**What happens / happened?**:
Client was crashed when I open page that AP block while creative mode.
Client was crashed when I was showing page related AP with JEI.
 
**Crash Report (via. [Pastebin](http://pastebin.com/))**:
Creative mode:
The game crashed whilst rendering item
Error: java.lang.NoSuchFieldError: field_78286_d

JEI:
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Already building!

**Comment by ghost** [comment]
Ah, sorry. already It was reported?

**Comment by sokratis12GR** [comment]
I can't seem to reproduce it but I'll release a fix for it to not happen if it is happening

**Comment by sokratis12GR** [comment]
@Piccot1214 does the latest version fix that crash ?

**Comment by ghost** [comment]
Very sorry for late replying.

I use this version.
armorplus-1.11.2-9.5.7.8-beta

But still crush. report here.

Creative Mode and Click AP Block Tab:
The game crashed whilst rendering item
Error: java.lang.NoSuchFieldError: field_78286_d

JEI:
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Already building!

**Comment by sokratis12GR** [comment]
could you provide me the **full** crashlog please ? :)

**Comment by Piccot1214** [comment]
<iframe src="//pastebin.com/embed_iframe/SVpaNFmi" style="border:none;width:100%"></iframe>

**Comment by Piccot1214** [comment]
<script src="//pastebin.com/embed_js/XeFbZq76"></script>

**Comment by ghost** [comment]
Sorry I don't know how to user pastebin.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 2/15/17 8:02 PM
Description: Rendering item

java.lang.NoSuchFieldError: field_78286_d
	at net.minecraftforge.client.model.SimpleModelFontRenderer.func_78266_a(SimpleModelFontRenderer.java:68)
	at net.minecraft.client.gui.FontRenderer.func_181559_a(FontRenderer.java:293)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java:562)
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:675)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:420)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:399)
	at net.minecraftforge.client.model.FancyMissingModel$BakedModel.func_188616_a(FancyMissingModel.java:146)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:168)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:140)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:203)
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:466)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:508)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:604)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:529)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1412)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.SimpleModelFontRenderer.func_78266_a(SimpleModelFontRenderer.java:68)
	at net.minecraft.client.gui.FontRenderer.func_181559_a(FontRenderer.java:293)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java:562)
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:675)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:420)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:399)
	at net.minecraftforge.client.model.FancyMissingModel$BakedModel.func_188616_a(FancyMissingModel.java:146)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:168)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:140)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:203)
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:466)

-- Item being rendered --
Details:
	Item Type: net.minecraft.item.ItemBlock@66557a82
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:508)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:604)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:529)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (378, 148). Absolute: (756, 603)
	Screen size: Scaled: (800, 450). Absolute: (1600, 900). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [PlayerOverride['Piccot'/347, l='MpServer', x=1290.27, y=35.06, z=-571.55]]
	Chunk stats: MultiplayerChunkCache: 4147, 4147
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (115,64,288), Chunk: (at 3,4,0 in 7,18; contains blocks 112,0,288 to 127,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 7508 game time, 7508 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 38 total; [EntityDemonPig['Demon Pig'/450, l='MpServer', x=1369.50, y=36.00, z=-515.50], EntityPigZombie['ゾンビピッグマン'/391, l='MpServer', x=1337.50, y=87.00, z=-546.50], EntityDemonPig['Demon Pig'/455, l='MpServer', x=1335.50, y=99.00, z=-613.50], EntityPigZombie['ゾンビピッグマン'/456, l='MpServer', x=1340.50, y=99.00, z=-612.50], EntityPigZombie['ゾンビピッグマン'/457, l='MpServer', x=1341.50, y=99.00, z=-612.50], EntityPigZombie['ゾンビピッグマン'/394, l='MpServer', x=1287.50, y=69.00, z=-544.50], EntityPigZombie['ゾンビピッグマン'/458, l='MpServer', x=1245.50, y=41.00, z=-534.50], EntityPigZombie['ゾンビピッグマン'/395, l='MpServer', x=1291.50, y=69.00, z=-544.50], EntityEnderman['エンダーマン'/402, l='MpServer', x=1232.50, y=87.00, z=-641.50], EntityPigZombie['ゾンビピッグマン'/468, l='MpServer', x=1366.50, y=36.00, z=-579.50], EntityPigZombie['ゾンビピッグマン'/469, l='MpServer', x=1365.50, y=36.00, z=-580.50], EntityPigZombie['ゾンビピッグマン'/470, l='MpServer', x=1365.50, y=36.00, z=-583.50], EntityPigZombie['ゾンビピッグマン'/471, l='MpServer', x=1364.50, y=36.00, z=-582.50], EntityDemonCow['Demon Cow'/411, l='MpServer', x=1358.50, y=15.00, z=-637.50], EntityDemonCow['Demon Cow'/412, l='MpServer', x=1211.50, y=84.00, z=-526.50], PlayerOverride['Piccot'/347, l='MpServer', x=1290.27, y=35.06, z=-571.55], EntityPigZombie['ゾンビピッグマン'/419, l='MpServer', x=1250.50, y=101.00, z=-493.50], EntityPigZombie['ゾンビピッグマン'/420, l='MpServer', x=1250.50, y=101.00, z=-494.50], EntityPigZombie['ゾンビピッグマン'/421, l='MpServer', x=1247.50, y=101.00, z=-493.50], EntityDemonPig['Demon Pig'/360, l='MpServer', x=1334.50, y=4.00, z=-526.50], EntityDemonSheep['Demon Sheep'/362, l='MpServer', x=1269.50, y=40.00, z=-592.50], EntityDemonSheep['Demon Sheep'/363, l='MpServer', x=1268.50, y=40.00, z=-594.50], EntityPigZombie['ゾンビピッグマン'/491, l='MpServer', x=1347.50, y=45.00, z=-502.50], EntityDemonSheep['Demon Sheep'/364, l='MpServer', x=1265.50, y=40.00, z=-595.50], EntityDemonSheep['Demon Sheep'/365, l='MpServer', x=1268.50, y=40.00, z=-591.50], EntityPigZombie['ゾンビピッグマン'/373, l='MpServer', x=1351.50, y=52.00, z=-564.50], EntityPigZombie['ゾンビピッグマン'/502, l='MpServer', x=1277.50, y=40.00, z=-542.50], EntityDemonChicken['Demon Chicken'/503, l='MpServer', x=1281.50, y=40.00, z=-544.50], EntityPigZombie['ゾンビピッグマン'/376, l='MpServer', x=1349.49, y=52.00, z=-562.22], EntityPigZombie['ゾンビピッグマン'/504, l='MpServer', x=1275.50, y=40.00, z=-543.50], EntityDemonChicken['Demon Chicken'/377, l='MpServer', x=1349.50, y=52.00, z=-564.65], EntityDemonChicken['Demon Chicken'/378, l='MpServer', x=1345.65, y=52.00, z=-560.93], EntityPigZombie['ゾンビピッグマン'/506, l='MpServer', x=1261.50, y=72.00, z=-497.50], EntityPigZombie['ゾンビピッグマン'/507, l='MpServer', x=1262.52, y=73.25, z=-497.73], EntityPigZombie['ゾンビピッグマン'/380, l='MpServer', x=1247.74, y=39.00, z=-560.55], EntityPigZombie['ゾンビピッグマン'/508, l='MpServer', x=1263.50, y=72.00, z=-497.50], EntityDemonSheep['Demon Sheep'/446, l='MpServer', x=1279.50, y=43.00, z=-550.50], EntityDemonSheep['Demon Sheep'/383, l='MpServer', x=1215.50, y=36.00, z=-572.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1245848136 bytes (1188 MB) / 2925948928 bytes (2790 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 3, tallocated: 104
	FML: MCP 9.38 Powered by Forge 13.20.0.2226 Optifine OptiFine_1.11.2_HD_U_B5 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2226.jar) 
	UCHIJAAAA	forge{13.20.0.2226} [Minecraft Forge] (forge-1.11.2-13.20.0.2226.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	bettercombatmod{1.4.0} [Better Combat] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
	UCHIJAAAA	jei{4.2.4.231} [Just Enough Items] (jei_1.11.2-4.2.4.231.jar) 
	UCHIJAAAA	abyssalcraft{1.9.3.10} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.3.10.jar) 
	UCHIJAAAA	thedragonlib{1.11.2-2.2.3} [TheDragonLib] (thedragonlib-1.11.2-2.2.3.jar) 
	UCHIJAAAA	armorplus{1.11.2-9.5.6.7-beta} [ArmorPlus] (armorplus-1.11.2-9.5.6.7-beta.jar) 
	UCHIJAAAA	bettersprinting{1.1.9} [Better Sprinting] (BetterSprinting  MC-1.11.2  v1.1.9.jar) 
	UCHIJAAAA	biomesoplenty{6.0.1.2145} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.1.2145-universal.jar) 
	UCHIJAAAA	chiselsandbits{13.9} [Chisels & Bits] (chiselsandbits-13.9.jar) 
	UCHIJAAAA	commandkeybindings{7.0.0} [Command Keybindings] (CommandKeybindings-Forge-7.0.0.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.11-5.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.11-5.1.jar) 
	UCHIJAAAA	hud{1.3.8} [Better HUD] (hud-1.3.8-1.11.jar) 
	UCHIJAAAA	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-77-7812cce} [Inventory Tweaks] (InventoryTweaks-1.62-dev-77.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHIJAAAA	justenoughdimensions{1.2.0} [Just Enough Dimensions] (justenoughdimensions-1.11.2-1.2.0.jar) 
	UCHIJAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAA	moredyes{@VERSION@} [More Dyes] (MoreDyes-1.11-1.1.1.jar) 
	UCHIJAAAA	moreoverlays{1.9} [MoreOverlays] (moreoverlays-1.9-mc1.11.jar) 
	UCHIJAAAA	realistictorches{2.1.0} [Realistic Torches] (RealisticTorches-1.11.2-2.1.0.jar) 
	UCHIJAAAA	torohealthmod{1.11.2-9} [ToroHealth Damage Indicators] (torohealth-1.11.2-9.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	wts{1.0.1} [What's That Slot] (WTS-1.0.1.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.26' Renderer: 'GeForce GTX 1060/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2226
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060/PCIe/SSE2 GL version 4.5.0 NVIDIA 369.26, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 日本語 (日本)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B5
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.5.0 NVIDIA 369.26
	OpenGlRenderer: GeForce GTX 1060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by sokratis12GR** [comment]
This issue is caused by optifine
Reference: `The NoSuchFieldError looks to have been an optifine issue: `https://github.com/sp614x/optifine/issues/438
