### ISSUE TITLE
[1.9.4] lava armor corrupted with latest version 2.4.1

### ISSUE THREAD

**Issue by benitomusolini** [sokratis12GR/ArmorPlus#22]
using forge 12.17.0.1940
lava armor is corrupted and displayed purple and black (file not found error).

Failed to load texture: armorplus:textures/models/armor/LavaArmor_layer_1.png
java.io.FileNotFoundException: armorplus:textures/models/armor/LavaArmor_layer_1.png
    at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bvw.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bwi.class:?]
    at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:34) ~[bva.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:79) [bvf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) [bvf.class:?]
    at net.minecraft.client.renderer.entity.Render.func_110776_a(Render.java:129) [brk.class:?]
    at net.minecraft.client.renderer.entity.layers.LayerArmorBase.func_188361_a(LayerArmorBase.java:76) [btg.class:?]
    at net.minecraft.client.renderer.entity.layers.LayerArmorBase.func_177141_a(LayerArmorBase.java:43) [btg.class:?]
    at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:486) [bsa.class:?]
    at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:209) [bsa.class:?]
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:70) [buh.class:?]
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28) [buh.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:378) [brj.class:?]
    at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:94) [bgi.class:?]
    at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:60) [bgi.class:?]
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76) [bfr.class:?]
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51) [bgc.class:?]
    at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47) [bgi.class:?]
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355) [ForgeHooksClient.class:?]
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at Reflector.callVoid(Reflector.java:309) [Reflector.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1398) [bnd.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1075) [bcd.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369) [bcd.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by sokratis12GR** [comment]
Fixed in 2.4.2
