### ISSUE TITLE
[1.11] Server crash in newest update

### ISSUE THREAD

**Issue by FuriousXtremes** [sokratis12GR/ArmorPlus#86]
I tried installing the mod to my server but for some reason it crashes:
Btw forge version is 13.19.1.2199

---- Minecraft Crash Report ----

WARNING: coremods are present:
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
CXLibraryCore (cxlibrary-1.11-1.3.0.jar)
FMLPlugin (InventoryTweaks-1.62-dev-74.jar)
llibrary (llibrary-1.7.2-1.11.jar)
BCModPlugin (zz-backpacks 1.11 - 3.1.5.jar)
MMFMLCorePlugin (MultiMine-1.11.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 12/24/16 1:11 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ArmorPlus (armorplus)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/IOUtils
at net.thedragonteam.armorplus.util.Logger.syncConfig(Logger.java:50)
at net.thedragonteam.armorplus.util.Logger.init(Logger.java:25)
at net.thedragonteam.armorplus.proxy.CommonProxy.preInit(CommonProxy.java:37)
at net.thedragonteam.armorplus.ArmorPlus.preInit(ArmorPlus.java:129)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:635)
at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:626)
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:329)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.IOUtils
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 35 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.11
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_112, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 469500192 bytes (447 MB) / 842530816 bytes (803 MB) up to 1895825408 bytes (1808 MB)
JVM Flags: 0 total; 
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.35 Powered by Forge 13.19.1.2199 44 mods loaded, 44 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCH minecraft{1.11} [Minecraft] (minecraft.jar) 
UCH mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
UCH FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.1.2199-universal.jar) 
UCH forge{13.19.1.2199} [Minecraft Forge] (forge-1.11-13.19.1.2199-universal.jar) 
UCH backpacks16840{3.1.5} [Backpacks!] (zz-backpacks 1.11 - 3.1.5.jar) 
UCH jei{4.1.1.207} [Just Enough Items] (jei_1.11-4.1.1.207.jar) 
UCH abyssalcraft{1.9.3.9} [AbyssalCraft] (AbyssalCraft-1.11-1.9.3.9.jar) 
UCH thedragonlib{1.11-2.0.1} [TheDragonLib] (thedragonlib-1.11-2.0.1.jar) 
UCE armorplus{1.11-9.2.0.1-beta} [ArmorPlus] (armorplus-1.11-9.2.0.1-beta.jar) 
UCH bdlib{1.13.0.7} [BD Lib] (bdlib-1.13.0.7-mc1.11.jar) 
UCH betterbuilderswands{0.9.3} [Better Builder's Wands] (BetterBuildersWands-1.11-0.9.3.194+16eed85.jar) 
UCH chancecubes{1.11-2.3.3.136} [Chance Cubes] (ChanceCubes-1.11-2.3.3.136.jar)
UCH chesttransporter{2.6.0} [Chest Transporter] (ChestTransporter-1.11-2.6.0.jar) 
UCH chiselsandbits{13.5} [Chisels & Bits] (chiselsandbits-13.5.jar) 
UCH cnoapm{1.0 by Dot_Silver} [Craftable Notch Apple Mod - MCVersion 1.11] (cnoapm-mcv1.11.jar) 
UCH cxlibrary{1.3.0} [CXLibrary] (cxlibrary-1.11-1.3.0.jar) 
UCH eleccore{1.6.358} [ElecCore] (ElecCore-1.11-1.6.358.jar) 
UCH deepresonance{1.4.1} [DeepResonance] (deepresonance-1.1x-1.4.1.jar) 
UCH glasscraftmod{2.0} [Glasscraft] (Glasscraftmod v2.0 - MC1.11 Forge.jar) 
UCH grimpack{4.0.0.0-alpha.1} [Grim Pack] (Grim Pack-1.11-4.0.0.0-alpha.1.jar) 
UCH furniture{1.0.4} [How 'Bout That Furniture] (HowBoutThatFurniture-1.0.4.jar) 
UCH waila{1.8.5} [Waila] (Hwyla-1.8.5-B19_1.11.jar) 
UCH inventorytweaks{1.62-dev-74-f3105ea} [Inventory Tweaks] (InventoryTweaks-1.62-dev-74.jar) 
UCH ironchest{1.11-7.0.17.799} [Iron Chest] (ironchest-1.11-7.0.17.799.jar) 
UCH journeymap{1.11-5.3.2} [JourneyMap] (journeymap-1.11-5.3.2.jar) 
UCH llibrary{1.7.2} [LLibrary] (llibrary-1.7.2-1.11.jar) 
UCH mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
UCH morefurnaces{1.9.0} [More Furnaces] (MoreFurnaces-1.11-1.9.0.jar) 
UCH shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.1.jar) 
UCH multibeds{1.3.1} [Multi-Beds] (multibeds-1.11.0-1.3.1.jar) 
UCH multimine{1.5.5} [Multi Mine] (MultiMine-1.11.jar) 
UCH mysticalagriculture{1.3.7} [Mystical Agriculture] (mysticalagriculture[1.11]-1.3.7b.jar) 
UCH oreexcavation{1.3.73} [OreExcavation] (OreExcavation-1.3.73.jar) 
UCH mc{1.7b} [Primordial Crops] (PrimordialCrops-v1.7b_mc1.11.jar) 
UCH reborncore{2.11.2.62} [RebornCore] (RebornCore-1.11-2.11.2.62-universal.jar) 
UCH reborncore-mcmultipart{2.11.2.62} [reborncore-MCMultiPart] (RebornCore-1.11-2.11.2.62-universal.jar) 
UCH refinedstorage{1.3.5} [Refined Storage] (refinedstorage-1.3.5.jar) 
UCH xreliquary{1.11-1.3.3.597} [Reliquary] (Reliquary-1.11-1.3.3.597.jar) 
UCH simulatednights{1.11-1.1.0} [Simulated Nights] (simulatednights-1.11-1.1.0.jar) 
UCH slabcraftmod{7.01} [Slabcraft] (Slabcraftmod v7.01 - MC1.11 Forge.jar) 
UCH techreborn{2.0.6.71} [TechReborn] (TechReborn-1.11-2.0.6.71-universal.jar) 
UCH thutcore{4.3.1} [ThutCore] (thutcore-4.3.1.jar) 
UCH thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) 
UCH wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.2.2.jar) 
Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
shetiphian.core.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.11-1.3.0.jar)
cubex2.cxlibrary.CoreModTransformer
FMLPlugin (InventoryTweaks-1.62-dev-74.jar)
invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-1.7.2-1.11.jar)
net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BCModPlugin (zz-backpacks 1.11 - 3.1.5.jar)
brad16840.common.asm.ClassTransformer
MMFMLCorePlugin (MultiMine-1.11.jar)
atomicstryker.multimine.common.fmlmagic.MMTransformer
List of loaded APIs: 
* AbyssalCraftAPI (1.8.8) from AbyssalCraft-1.11-1.9.3.9.jar
* ArmorPlusApi (2.0) from armorplus-1.11-9.2.0.1-beta.jar
* ChiselsAndBitsAPI (12.5.0) from chiselsandbits-13.5.jar
* CoFHAPI (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.1.jar
* CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.1.jar
* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.1.jar
* compatlayer (0.1.4) from compatlayer-1.11-0.1.4.jar
* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.1.jar
* ElecCoreAPI (1.0) from ElecCore-1.11-1.6.358.jar
* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.6.358.jar
* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11-5.3.2.jar
* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11-5.3.2.jar
* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11-5.3.2.jar
* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11-5.3.2.jar
* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11-5.3.2.jar
* JustEnoughItemsAPI (4.11.0) from jei_1.11-4.1.1.207.jar
* mcjtylib_ng (2.3.1) from mcjtylib-1.1x-2.3.1.jar
* reborncoreAPI (2.11.2.62) from RebornCore-1.11-2.11.2.62-universal.jar
* reborncoreAPI|Fuel (2.11.2.62) from RebornCore-1.11-2.11.2.62-universal.jar
* reborncoreAPI|Power (2.11.2.62) from RebornCore-1.11-2.11.2.62-universal.jar
* reborncoreAPI|Recipe (2.11.2.62) from RebornCore-1.11-2.11.2.62-universal.jar
* reborncoreAPI|Tile (2.11.2.62) from RebornCore-1.11-2.11.2.62-universal.jar
* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
* techrebornAPI (2.0.6.71) from TechReborn-1.11-2.0.6.71-universal.jar
* thut|API (1.0.0) from thutcore-4.3.1.jar
* WailaAPI (1.3) from Hwyla-1.8.5-B19_1.11.jar
Profiler Position: N/A (disabled)
Is Modded: Definitely; Server brand changed to 'fml,forge'
Type: Dedicated Server (map_server.txt)

**Comment by sokratis12GR** [comment]
Thanks for the report. Fixed in the upcoming version 1.11-9.3.0.1-beta
